Update performance_test.yml

diff --git a/.github/workflows/performance_test.yml b/.github/workflows/performance_test.yml
--- a/.github/workflows/performance_test.yml
+++ b/.github/workflows/performance_test.yml
@@ -83,21 +83,21 @@ jobs:
             ccv2_build_url="${{env.CCV2_BASE_URL}}/builds";
             payload='{"branch": "${{ env.BRANCH_NAME}}", "name": "'"${{ env.BUILD_NAME }}"'"}';
             echo "Payload :: $payload"
-            buildcode=$(curl --location --request POST "$ccv2_build_url" --header 'Content-Type: application/json' --header "Authorization: Bearer ${{env.ACCESS_TOKEN}}" --data-raw "$payload" | jq '.code')
+            #buildcode=$(curl --location --request POST "$ccv2_build_url" --header 'Content-Type: application/json' --header "Authorization: Bearer ${{env.ACCESS_TOKEN}}" --data-raw "$payload" | jq '.code')
             echo "buildcode=$buildcode" >> $GITHUB_ENV
-            sleep 300
+            #sleep 300
             echo "Create Build Response:  $buildcode"
             ##########
-            if [ "$buildcode" == "null" ] || [ -z "$buildcode" ]; then
-              echo "Build creation failed!"
-              finalStatus="FAIL"
-              echo "FINAL_BUILD_STATUS=$finalStatus" >> $GITHUB_ENV
-              exit 1 # Fail the workflow, but the next step can still run if you want it to.
-            else
-              echo "buildcode=$buildcode" >> $GITHUB_ENV
-              finalStatus="IN_PROGRESS"
-              echo "FINAL_BUILD_STATUS=$finalStatus" >> $GITHUB_ENV
-            fi
+            #if [ "$buildcode" == "null" ] || [ -z "$buildcode" ]; then
+            #  echo "Build creation failed!"
+            #  finalStatus="FAIL"
+            #  echo "FINAL_BUILD_STATUS=$finalStatus" >> $GITHUB_ENV
+            #  exit 1 # Fail the workflow, but the next step can still run if you want it to.
+            #else
+            #  echo "buildcode=$buildcode" >> $GITHUB_ENV
+            #  finalStatus="IN_PROGRESS"
+            #  echo "FINAL_BUILD_STATUS=$finalStatus" >> $GITHUB_ENV
+            #fi
             ##########
             echo "::set-output name=buildcode::$buildcode" # Set the buildCode as an output for other jobs
           shell: bash
@@ -112,7 +112,7 @@ jobs:
                 echo "checkBuild buildcode : ${{ env.buildcode }}"
                 progress_ccv2_build_url="$ccv2_build_url/${{ env.buildcode }}/progress"
                 echo "URL: $progress_ccv2_build_url"
-                buildresponse=$(curl --location --request GET "$progress_ccv2_build_url" --header "Authorization: Bearer ${{env.ACCESS_TOKEN}}")
+                #buildresponse=$(curl --location --request GET "$progress_ccv2_build_url" --header "Authorization: Bearer ${{env.ACCESS_TOKEN}}")
                 buildStatus=$(jq -n "$buildresponse" | jq '.buildStatus')
                 percentage=$(jq -n "$buildresponse" | jq '.percentage')
                 echo "Check Progress Status: $buildStatus" 
@@ -161,7 +161,7 @@ jobs:
               echo "databaseUpdateMode: ${{ env.DATABASE_UPDATE_MODE }}"
               echo "strategy: ${{ env.DEPLOYMENT_STRATEGY }}"
               echo "buildCode: $buildcode"
-              DepCode=`curl -X POST $ccv2_deployment_url -H "Authorization: Bearer ${{env.ACCESS_TOKEN}}" -H "Content-Type: application/json" -d '{"buildCode": ${{ needs.build-branch.outputs.build_code }},  "databaseUpdateMode": "${{ env.DATABASE_UPDATE_MODE }}",  "environmentCode": "${{ env.ENVIRONMENT_CODE }}",  "strategy": "${{ env.DEPLOYMENT_STRATEGY }}"}' | jq -r 'values.code'`
+              #DepCode=`curl -X POST $ccv2_deployment_url -H "Authorization: Bearer ${{env.ACCESS_TOKEN}}" -H "Content-Type: application/json" -d '{"buildCode": ${{ needs.build-branch.outputs.build_code }},  "databaseUpdateMode": "${{ env.DATABASE_UPDATE_MODE }}",  "environmentCode": "${{ env.ENVIRONMENT_CODE }}",  "strategy": "${{ env.DEPLOYMENT_STRATEGY }}"}' | jq -r 'values.code'`
               sleep 300
               echo $DepCode
               echo "DepCode=$DepCode" >> $GITHUB_ENV
@@ -179,7 +179,7 @@ jobs:
                  ccv2_deployment_progress_url="$ccv2_deployment_url/${{env.DepCode}}/progress"
                  echo "URL: $progress_ccv2_deployment_url"
                  deploymentresponse=$(curl --location --request GET "$ccv2_deployment_progress_url" --header "Authorization: Bearer ${{env.ACCESS_TOKEN}}")
-                 deploymentStatus=$(jq -n "$deploymentresponse" | jq '.deploymentStatus')
+                # deploymentStatus=$(jq -n "$deploymentresponse" | jq '.deploymentStatus')
                  percentage=$(jq -n "$deploymentresponse" | jq '.percentage')
                  echo "Check Progress Status: $deploymentStatus"
                  if [ $deploymentStatus = '"DEPLOYED"' ];then
